const DEFAULT_IMAGE = "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop";

const sampleListings = [
  {
    title: "Serene Mountain Cabin",
    description: "Escape to this peaceful cabin in Manali, offering breathtaking views of the snow-capped Himalayas.",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=600&fit=crop",
    price: 3800,
    location: "Manali, Himachal Pradesh",
    country: "India",
  },
  {
    title: "Luxury Goan Villa with Pool",
    description: "A stunning villa with a private pool, just a stone's throw away from the vibrant Anjuna Beach.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
    price: 13000,
    location: "Anjuna, Goa",
    country: "India",
  },
  {
    title: "Royal Jaipur Haveli",
    description: "Step back in time with a stay at this beautifully restored heritage haveli in the heart of Jaipur.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    price: 4700,
    location: "Jaipur, Rajasthan",
    country: "India",
  },
  {
    title: "Alleppey Backwaters Houseboat",
    description: "Experience the magic of Kerala on a traditional Kettuvallam, floating through serene backwaters.",
    image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&h=600&fit=crop",
    price: 8000,
    location: "Alleppey, Kerala",
    country: "India",
  },
  {
    title: "Rishikesh Ganges Retreat",
    description: "A peaceful retreat for yoga and meditation enthusiasts, located on the banks of the holy Ganges.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    price: 2500,
    location: "Rishikesh, Uttarakhand",
    country: "India",
  },
  {
    title: "Ooty Tea Estate Bungalow",
    description: "A charming colonial bungalow nestled amidst sprawling tea gardens with panoramic valley views.",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    price: 6000,
    location: "Ooty, Tamil Nadu",
    country: "India",
  },
  {
    title: "Udaipur Lakefront Palace",
    description: "Indulge in luxury at this magnificent hotel offering stunning views of Lake Pichola.",
    image: "https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?w=800&h=600&fit=crop",
    price: 16000,
    location: "Udaipur, Rajasthan",
    country: "India",
  },
  {
    title: "Ladakh Mountain Guesthouse",
    description: "A cozy guesthouse in Leh offering spectacular views of the rugged mountains and clear blue skies.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&h=600&fit=crop",
    price: 3000,
    location: "Leh, Ladakh",
    country: "India",
  },
  {
    title: "Darjeeling Himalayan View Hotel",
    description: "Wake up to majestic views of Kanchenjunga from this charming heritage hotel in Darjeeling.",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    price: 6500,
    location: "Darjeeling, West Bengal",
    country: "India",
  },
  {
    title: "Modern Mumbai Apartment",
    description: "A stylish and contemporary apartment with stunning sea views in the heart of Bandra.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    price: 9800,
    location: "Mumbai, Maharashtra",
    country: "India",
  },
  {
    title: "Shillong Forest Cabin",
    description: "A rustic wooden cabin nestled in the pine forests of Shillong, perfect for a tranquil escape.",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    price: 3400,
    location: "Shillong, Meghalaya",
    country: "India",
  },
  {
    title: "Pondicherry Colonial Homestay",
    description: "Experience French colonial charm in this elegant homestay located in the historic White Town.",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
    price: 4200,
    location: "Pondicherry, Puducherry",
    country: "India",
  },
  {
    title: "Jaisalmer Desert Luxury Camp",
    description: "Spend a night under the stars in a luxurious tent in the Thar Desert, complete with a camel safari.",
    image: "https://images.unsplash.com/photo-1610530531783-56a4e92a3305?w=800&h=600&fit=crop",
    price: 5800,
    location: "Jaisalmer, Rajasthan",
    country: "India",
  },
  {
    title: "Coorg Plantation Stay",
    description: "A serene homestay set within a sprawling coffee plantation, offering nature walks and fresh brews.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
    price: 4000,
    location: "Coorg, Karnataka",
    country: "India",
  },
  {
    title: "Varanasi Ghats Guesthouse",
    description: "A traditional guesthouse offering an immersive experience of life on the sacred ghats of Varanasi.",
    image: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
    price: 2000,
    location: "Varanasi, Uttar Pradesh",
    country: "India",
  },
  {
    title: "Hampi Boulders Resort",
    description: "A unique resort near the Hampi ruins, with cottages set amidst the region's iconic boulders.",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
    price: 5000,
    location: "Hampi, Karnataka",
    country: "India",
  },
  {
    title: "Spiti Valley Homestay",
    description: "Experience the local culture and warm hospitality of Spiti in this traditional homestay in Kaza.",
    image: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&h=600&fit=crop",
    price: 1600,
    location: "Kaza, Himachal Pradesh",
    country: "India",
  },
  {
    title: "Munnar Tea Garden Resort",
    description: "A luxury resort with an infinity pool offering breathtaking views of the rolling tea hills of Munnar.",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
    price: 7000,
    location: "Munnar, Kerala",
    country: "India",
  },
  {
    title: "Andaman Beachfront Hut",
    description: "A rustic and charming beach hut on Havelock Island, just steps from the pristine white sands.",
    image: "https://images.unsplash.com/photo-1602391833977-358a52198938?w=800&h=600&fit=crop",
    price: 3200,
    location: "Havelock Island, Andaman & Nicobar Islands",
    country: "India",
  },
  {
    title: "Chic Delhi Studio",
    description: "A stylish studio apartment in a quiet South Delhi neighborhood, perfect for solo travelers or couples.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    price: 4500,
    location: "New Delhi, Delhi",
    country: "India",
  },
  {
    title: "Kodaikanal Hillside Cottage",
    description: "A cozy cottage with a fireplace, offering stunning views of the valley and Kodaikanal Lake.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    price: 5200,
    location: "Kodaikanal, Tamil Nadu",
    country: "India",
  },
  {
    title: "Auli Mountain Ski Lodge",
    description: "A rustic lodge offering ski-in/ski-out access and panoramic views of the Nanda Devi peak.",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
    price: 7500,
    location: "Auli, Uttarakhand",
    country: "India",
  },
  {
    title: "Gokarna Beachside Shack",
    description: "A simple and laid-back shack on Kudle Beach, perfect for watching sunsets over the Arabian Sea.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
    price: 1400,
    location: "Gokarna, Karnataka",
    country: "India",
  },
  {
    title: "Amritsar Golden Temple Homestay",
    description: "A clean and modern homestay offering warm Punjabi hospitality, located near the Golden Temple.",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    price: 2800,
    location: "Amritsar, Punjab",
    country: "India",
  },
  {
    title: "Thekkady Spice Plantation Villa",
    description: "Stay in a villa surrounded by fragrant spice plantations, with opportunities for nature tours.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    price: 6200,
    location: "Thekkady, Kerala",
    country: "India",
  },
  {
    title: "Historic Kolkata Guesthouse",
    description: "Experience the charm of old Calcutta in this well-preserved colonial-era guesthouse.",
    image: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
    price: 3500,
    location: "Kolkata, West Bengal",
    country: "India",
  },
  {
    title: "Kasol Parvati Valley Camp",
    description: "A scenic campsite nestled by the Parvati River, ideal for trekkers and nature lovers.",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    price: 2000,
    location: "Kasol, Himachal Pradesh",
    country: "India",
  },
  {
    title: "Mahabalipuram Shore Resort",
    description: "A beautiful resort with direct beach access, located close to the historic Shore Temple.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
    price: 7800,
    location: "Mahabalipuram, Tamil Nadu",
    country: "India",
  },
  {
    title: "Agra Homestay with Taj View",
    description: "A family-run homestay with a rooftop terrace offering a direct, stunning view of the Taj Mahal.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    price: 3100,
    location: "Agra, Uttar Pradesh",
    country: "India",
  },
  {
    title: "Dharamshala Mountain Inn",
    description: "A peaceful inn in McLeod Ganj offering clear views of the Dhauladhar range and Tibetan monasteries.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
    price: 2700,
    location: "Dharamshala, Himachal Pradesh",
    country: "India",
  },
  {
    title: "Pushkar Lake View Hotel",
    description: "A vibrant and colorful hotel with a relaxing pool, located near the sacred Pushkar Lake.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    price: 3600,
    location: "Pushkar, Rajasthan",
    country: "India",
  },
  {
    title: "Srinagar Dal Lake Houseboat",
    description: "An exquisite wooden houseboat on Dal Lake, offering a unique and serene Kashmiri experience.",
    image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&h=600&fit=crop",
    price: 6000,
    location: "Srinagar, Jammu & Kashmir",
    country: "India",
  },
  {
    title: "Mysore Heritage Home",
    description: "A comfortable guesthouse with a view of the beautifully illuminated Mysore Palace at night.",
    image: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
    price: 2600,
    location: "Mysore, Karnataka",
    country: "India",
  },
  {
    title: "Gangtok Monastery View Homestay",
    description: "A warm and simple homestay offering incredible views of the famous Rumtek Monastery.",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
    price: 1900,
    location: "Gangtok, Sikkim",
    country: "India",
  },
  {
    title: "Pahalgam Valley Resort",
    description: "A beautiful resort nestled in the Aru Valley, surrounded by lush meadows and pristine rivers.",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    price: 7200,
    location: "Pahalgam, Jammu & Kashmir",
    country: "India",
  },
  {
    title: "Bodh Gaya Spiritual Retreat",
    description: "A serene and minimalist retreat center for those on a spiritual journey near the Mahabodhi Temple.",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
    price: 1700,
    location: "Bodh Gaya, Bihar",
    country: "India",
  },
  {
    title: "Wayanad Rainforest Treehouse",
    description: "Live amidst the canopy in a luxurious treehouse, deep in the lush rainforests of Wayanad.",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
    price: 9000,
    location: "Wayanad, Kerala",
    country: "India",
  },
  {
    title: "Chikmagalur Coffee Estate Loft",
    description: "A modern loft with glass walls overlooking a vast coffee estate. Perfect for a private retreat.",
    image: "https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?w=800&h=600&fit=crop",
    price: 9500,
    location: "Chikmagalur, Karnataka",
    country: "India",
  },
  {
    title: "Jodhpur Blue City Haveli",
    description: "An authentic haveli in the blue city with a rooftop restaurant offering views of Mehrangarh Fort.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    price: 4500,
    location: "Jodhpur, Rajasthan",
    country: "India",
  },
  {
    title: "Sundarbans Riverside Lodge",
    description: "An eco-lodge at the edge of the Sundarbans National Park, offering guided boat safaris.",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    price: 5300,
    location: "Sundarbans, West Bengal",
    country: "India",
  },
  {
    title: "Nainital Lake View Apartment",
    description: "A well-furnished apartment offering a peaceful stay with a beautiful, direct view of Naini Lake.",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    price: 4100,
    location: "Nainital, Uttarakhand",
    country: "India",
  },
  {
    title: "Pune Serviced Apartment",
    description: "A modern, fully-equipped serviced apartment in Koregaon Park, ideal for business and leisure.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    price: 4800,
    location: "Pune, Maharashtra",
    country: "India",
  },
  {
    title: "Varkala Cliffside Stay",
    description: "A charming cottage perched on the Varkala cliff, with stunning sunset views over the Arabian Sea.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
    price: 3900,
    location: "Varkala, Kerala",
    country: "India",
  },
  {
    title: "Orchha Riverside Retreat",
    description: "A tranquil hotel on the banks of the Betwa River with views of the historic Orchha cenotaphs.",
    image: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
    price: 3800,
    location: "Orchha, Madhya Pradesh",
    country: "India",
  },
  {
    title: "Rann of Kutch Tent Stay",
    description: "A traditional tent stay offering an authentic experience of the Great Rann of Kutch.",
    image: "https://images.unsplash.com/photo-1610530531783-56a4e92a3305?w=800&h=600&fit=crop",
    price: 5000,
    location: "Kutch, Gujarat",
    country: "India",
  },
  {
    title: "Bandhavgarh Jungle Lodge",
    description: "A rustic jungle lodge on the outskirts of Bandhavgarh National Park, ideal for wildlife enthusiasts.",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
    price: 6500,
    location: "Bandhavgarh, Madhya Pradesh",
    country: "India",
  },
  {
    title: "Chennai Beach House",
    description: "A modern beach house on the East Coast Road with a private garden and direct access to the sea.",
    image: "https://images.unsplash.com/photo-1602391833977-358a52198938?w=800&h=600&fit=crop",
    price: 11000,
    location: "Chennai, Tamil Nadu",
    country: "India",
  },
  {
    title: "Ahmedabad Heritage Home",
    description: "Stay in a traditional Pol house in the old city of Ahmedabad, a UNESCO World Heritage site.",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
    price: 4300,
    location: "Ahmedabad, Gujarat",
    country: "India",
  },
  {
    title: "Shimla Colonial Villa",
    description: "An elegant colonial-era villa offering panoramic views of the Shimla valley.",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    price: 8500,
    location: "Shimla, Himachal Pradesh",
    country: "India",
  },
];

const enrichedListings = sampleListings.map(listing => ({
  ...listing,
  image: listing.image || DEFAULT_IMAGE
}));

module.exports = { data: enrichedListings };